FORMAT: 1A
HOST: https://acurianauthformapidev.azurewebsites.net

# Chartfill API

Note: here are the envs for Chartfill:

DEV: https://acurianauthformapidev.azurewebsites.net

QA: https://acurianauthformapidev-qa.azurewebsites.net

STAGING: nothing yet, TODO: GET FROM CHARTFILL

PROD: nothing yet, TODO: GET FROM CHARTFILL


Polls is a simple API allowing consumers to view polls and vote in them.

## Create Chartfill Link for OLS embedded flow [/api/home/incomingfeed]
### Create Chartfill Link for OLS embedded flow [POST]

+ Request 200 (application/json)
    + Headers
    
            API_KEY: an api secret/key will be passed here like a1b2c2d3-ijkl-1234-abcd-abcdefghijkl Note: there will be a different key per instance
            
    + Attributes
        + PatientID (number, required)
        + SiteNumber (string, required)
        + ProjectCode (string, required) - We'll pass the Final(aka Child) Project Code here if this is a generic 'super-screener' (and the regular standalone project code if a non-super-screener)
        + OriginalProjectCode (string, required) - just for storage purposes as useful to see where user came from (like AMS1)
        + PatientFirstName (string, required)
        + PatientLastName (string, required)
        + PatientEmail (string) - this is usually required, but becomes optional field that won't get used if CaregiverFlow is true since CaregiverEmail becomes the person who gets emailed. If this is provided, maybe this person can be CCed on the signature (I would confirm this though as we aren't doing this currently I think. TODO: ACURIAN TO CONFIRM)
        + PatientPhone (string) - this is usually required, but becomes optional field that won't get used if CaregiverFlow is true.
        + PatientDOB (string) - This string is in a date format like: "1960-01-01"
        + IsCaregiverFlow (boolean, required) - can send this as true if its Caregiver flow... or false (or dont send at all if its normal Patient flow)
        + CaregiverFirstName (string, optional) - if CaregiverFlow boolean is true, this is required
        + CaregiverLastName (string, optional) - if CaregiverFlow boolean is true, this is required
        + CaregiverEmail (string, optional)  - if CaregiverFlow boolean is true, this is required
        + CaregiverPhone (string, optional)  - if CaregiverFlow boolean is true, this is optional (not sure if this is a required field in our Caregiver flow, double-check that, then this will always be passed then)
        + IsTest (boolean, required) - states whether to treat this in 'test' mode' aka don't send to the real production distribution list but the test dist list
        + IsCallCenter (boolean, required) - if this flag is true, then Chartfill will email the patient the link on behalf of Acurian (Note: if Nate prefers this, then I'll remove the 2nd separate CallCenter API call i setup below this one)
        + Locale (string) - locale like en_US (or dash en-US, maybe ask what is preferable)
        + REMOVE???_ENV (string) - not sure if we def going to remove this yet.
        + REMOVE???_Indication (string) - example: "Cancer Or Some Other Indication" CF-Nate- May not need this field due to new auth forms on CF side... Arian: may need to pass 'Final(aka Child) Project Code' if removing this field, see comment above^
                
    + Body
    
            {
                PatientID: "101010101",
                SiteNumber: "10111",
                ProjectCode: "3485",
                OriginalProjectCode: "AMS1",
                Indication: "Cancer Or Some Other Indication",
                PatientFirstName: "Arian",
                PatientLastName: "Hojat",
                PatientDOB: "1960-01-01",
                PatientPhone: "2151231234",
                PatientEmail: "arian.hojat@acurian.com",
                
                IsCaregiverFlow: true,
                CaregiverFirstName: "John",
                CaregiverLastName: "Smith",
                CaregiverEmail: "caregiver@caregiver.com",
                CaregiverPhone: "2159876543",
                IsTest: false,
                IsCallCenter: false
            }


+ Response 200 (application/json)
    + Attributes
        + Url (string) - url to embed in online screener
        + ReUsedUrl (boolean) - if a url/form is returned, but the url is a saved old url/form (which brings in old data), this would be good to know so we dont raise 'old data' issues to Chartfill
        + Status (string) - usually "Success"
    
    + Body
    
            {
                Url : "url",
                Status: "Success"
            } 


+ Response 401 (application/json)
    + Attributes - UPDATE: Error code now returns 401
        + Status (string) - 
        + ErrorType (string) - 
        + ErrorMessage (string) -
    
    + Body
    
            {
                ErrorType = "Authentication",
                ErrorMessage = "Invalid Key",
                Status = "Rejected"
            }

+ Response 406 (application/json)
    + Attributes - UPDATE: Error code now returns 406 (Precondition Failed)
        + Status (string) - 
        + ErrorType (string) - 
        + ErrorMessage (string) - 
    
    + Body
    
            {
                ErrorType = "Duplicate",
                ErrorMessage = "Already Signed",
                Status = "Rejected"
            }


+ Response 412 (application/json)
    + Attributes - UPDATE: Error code now returns 412 (Not Acceptable)
        + Status (string) - 
        + ErrorType (string) - 
        + ErrorMessage (string) - what if multiple fields have a validation error? CF- Every field will be separated by "; "
    
    + Body
    
            {
                ErrorType = "Invalid Input",
                ErrorMessage = "(missing field name)",
                Status = "Rejected"
            }




## Acurian callback API [/as/api/ChartFill/v1/saveChartFillData]
### Callback API [POST]

dev:       https://dev-as.acurian.com
qa:        https://qa-as.acurian.com
staging:   https://stg-as.acurian.com
prod:      https://as.acurian.com


+ Request 200 (application/json)
    + Headers
    
            Authorization: Use Basic Auth with the supplied user/pass. Please look up how to use Basic Auth header (i can kinda see in Postman how its supposed to look like).
            
    + Attributes
        + patientId (number, required) - 
        + childPatientId (number, optional) - only send over if Chartfill has it. They may not yet.
        + siteNumber (string, required) - send back with leading zeros if the site has any
        + projectCode (string)
        + originalProjectCode (string)
        + patientFirstName (string)
        + patientLastName (string)
        + patientEmail (string)
        + patientPhone (string)
        + patientDOB (string)
        + isCaregiverFlow (string) - up to you how to pass back this boolean via this string field: "True" or "true" or "Y", your choice.
        + caregiverFirstName (string)
        + caregiverLastName (string)
        + caregiverEmail (string)
        + caregiverPhone (string) - 06/28: hmmm not sure api added this , double-check and ask DB team to add if needed
        + caregiverRelationship (string)
        + isTest (string) - up to you how to pass back this boolean via this string field: "True" or "true" or "Y"; your choice.
        + isCallCenter (string) - up to you how to pass back this boolean via this string field: "True" or "true" or "Y"; your choice.
        + locale (string)
        + doctorName (string)
        + doctorPhone (string)
        + doctorAddress (string)
        + doctorCity (string)
        + doctorState (string)
        + doctorZip (string)
        + doctorTwoName (string)
        + doctorTwoPhone (string)
        + doctorTwoAddress (string)
        + doctorTwoCity (string)
        + doctorTwoState (string)
        + doctorTwoZip (string)
        + taname (string) - up to you how to pass back this boolean via this string field: "True" or "true" or "Y"; your choice.
        + drugBox (string) - up to you how to pass back this boolean via this string field: "True" or "true" or "Y"; your choice.
        + mentalBox (string) - up to you how to pass back this boolean via this string field: "True" or "true" or "Y"; your choice.
        + geneticBox (string) - up to you how to pass back this boolean via this string field: "True" or "true" or "Y"; your choice.
        + token (string)
        + patientStatus (string, required) - use one of the ENUMS we came up with: [MR_RECORDS_EN_ROUTE_TO_SITE, MR_RETRIEVING_RECORDS, MR_RETRIEVING_DOCTOR_INFO, MR_MISSING_DOCTOR_INFO, MR_INCORRECT_DOCTOR_INFO, ARRIVED_DR_LOOKUP_PAGE, ARRIVED_ESIGN_PAGE, SIGNED, REJECTED, CANCELLED, SOMEONE_ELSE_SIGNED]
        + authFormurl (string)
        + createdDate (string)
        + modifiedDate (string)
        + agreementId (string)
        + agreementFormurl (string)

    + Body
    
            {
                "patientId": 28924635,
                "childPatientId": 106678599, 
                "siteNumber":"010101",
                "projectCode":"2485",
                "originalProjectCode":"AMS1",
                "patientFirstName":"John",
                "patientLastName":"Smith",
                "patientEmail":"john.smith@gmail.com",
                "patientPhone":"215-990-0519",
                "patientDOB":"06/31/1960",
                "isCaregiverFlow":"True",
                "caregiverFirstName":"Jane",
                "caregiverLastName":"Smith",
                "caregiverEmail":"jane.smith@gmail.com",
                "caregiverRelationship":"Parent",
                "isTest":"True",
                "isCallCenter":"True",
                "locale":"en_US"
                "doctorName":"Roberto Panis", 
                "doctorPhone":"8001231234", 
                "doctorAddress":"2 Walnut Drive",
                "doctorCity":"Horsham",
                "doctorState":"PA",
                "doctorZip":"19044",
                "doctorTwoName":"Second Doctor", 
                "doctorTwoPhone":"8004567890",
                "doctorTwoAddress":"500 Fairmount Ave",
                "doctorTwoCity":"Philadelphia",
                "doctorTwoState":"PA",
                "doctorTwoZip":"19123",
                "taname": "",
                "drugBox":"True",
                "hivBox":"False",
                "mentalBox":"False",
                "geneticBox":"True",
                "token":"aed87571bfd3c73b7ff9920eafd10fc510fdd1a1",
                "patientStatus":"MR_RECORDS_EN_ROUTE_TO_SITE",
                "authFormurl":"http://chartfill.com/etc",
                "createdDate": "06/18/2019 23:30:15",
                "modifiedDate":"06/19/2019 23:30:15",
                "agreementId":"aed87571bfd3c73b7ff9920eafd10fc510fdd1a1",
                "agreementFormurl":"https://secure.na2.echosign.com/public/apiesign?pid=CBFCIBAA3AAABLblqZhB3Bww1jjUe8yKs5qWFLawePzJaznshxvudXLFmVQaSVqX_rrjk1cw_44SpD41Wvjg*"
            }

+ Response 200 (application/json)
    + Attributes - UPDATE: Error code now returns 412 (Not Acceptable)
        + apiResponse (object)
        + apiErrors (object) 
    
    + Body
    
            {
                "apiResponse": {
                    "chartFillDataSave": "ChartFill Data Saved successfully"
                },
                "apiErrors": [
                    {
                        "code": 200,
                        "status": "SUCCESSFULLY_SAVED",
                        "message": "patient data successfully saved",
                        "moreInfo": "patient data successfully saved",
                        "httpStatus": "OK",
                        "versionInfo": "Supported"
                    }
                ]
            }